# ===========================================
#  Sample config.toml for test_controller.py.
# ===========================================

# ----- General variables ----- #
# --- URLs --- #
pub_url = 'tcp://127.0.0.1:7776'
server_url = 'tcp://127.0.0.1:7777'
psc_url = 'tcp://127.0.0.1:7778'
router_url = 'tcp://127.0.0.1:7779'

# --- Timing --- #
timeout_ms = 5000
scan_wait_ms = 180000


# ----- PubSub ----- #
[pub]
class = 'afspm.io.pubsub.publisher.Publisher'
url = 'pub_url'

[psc]
class = 'afspm.io.pubsub.cache.PubSubCache'
url = 'psc_url'
sub_url = 'pub_url'

# ----- Control Logic ----- #
[server]
class = 'afspm.io.control.server.ControlServer'
url = 'server_url'

[router]
class = 'afspm.io.control.router.ControlRouter'
server_url = 'server_url'
router_url = 'router_url'


# ----- Components ----- #
[devcon]
component = true
class = 'afspm.components.device.controllers.gxsm.controller.GxsmController'
publisher = 'pub'
control_server = 'server'
read_use_physical_units = 'False'

[afspmcon]
component = true
class = 'afspm.components.afspm.controller.AfspmController'
pubsubcache = 'psc'
router = 'router'
